### ISSUE TITLE
KeyError when running SCDV.py 200 6 on Reuters

### ISSUE THREAD

**Issue by bernardmizzi** [dheeraj7596/SDV#2]
Good afternoon,

I am running python SCDV.py 200 60 on the Reuters set and the below error is occurring, can you kindly assist?

Traceback (most recent call last):
  File "SCDV.py", line 161, in <module>
    prob_wordvecs = get_probability_word_vectors(featurenames, word_centroid_map, num_clusters, word_idf_dict)
  File "SCDV.py", line 61, in get_probability_word_vectors
    prob_wordvecs[word][index*num_features:(index+1)*num_features] = model[word] * word_centroid_prob_map[word][index] * word_idf_dict[word]
KeyError: u'here'

**Comment by vgupta123** [comment]
Hi,

Your dictionary might not have some words. It is happening because the model vocab, idf vocab and word idf dict might be different. 

A very simple fix it put a try and except to ignore such word or check that your vocab have a word before accesing it. Hope this help you and aplogies to delayed responce.

Kindly let me know if you have any other question *my email: keviv9@gmail.com*

Thank You
